page userRanking.html.twig userManager userController Connection
WildCodeSchool/yellowgreen pull request #11
Opened 2022-11-02 09:36 UTC by serhanif59

2022-11-02 09:58 UTC, marcosigis approved these changes
just need to change user.name to user.nickName to correctly show the pseudo

2022-11-02 09:58 UTC, marcosigis commented on src/View/User/userRanking.html.twig
> +					<td class="left-justify">{{user.name}}</td>
in the updated database it was nickName right? just need to change this so it display the nickname

2022-11-03 08:22 UTC, marcosigis approved these changes

2022-11-03 10:42 UTC, Benja-san requested changes

2022-11-03 10:42 UTC, Benja-san commented on public/assets/js/header.js
> +console.log("blop");
I assume console.log is for debugging, could you remove it ?

2022-11-03 10:42 UTC, Benja-san commented on src/View/User/index.html.twig
> +					<! pour le moment sans Session !>
please use commenting symfony expressions {#...#}

2022-11-03 11:33 UTC, Benja-san approved these changes

2022-11-03 11:33 UTC, merged