Input secure
WildCodeSchool/yellowgreen pull request #28
Opened 2022-11-04 11:15 UTC by marcosigis

2022-11-04 11:30 UTC, Benja-san requested changes

2022-11-04 11:30 UTC, Benja-san commented on src/Controller/UserController.php
> +                $errors[] = "Entreè(s) avec format invalide";
"Entrées"

2022-11-04 11:30 UTC, Benja-san commented on src/Controller/UserController.php
> +                } catch (PDOException $err) {
try to put all PDO Exceptions (and try catch) inside manager class since it is related to database connexion

2022-11-08 09:29 UTC, Benja-san approved these changes

2022-11-08 09:35 UTC, serhanif59 approved these changes

2022-11-08 09:35 UTC, merged