Unicorn choice
WildCodeSchool/yellowgreen pull request #40
Opened 2022-11-08 16:12 UTC by thenriet

2022-11-08 16:17 UTC, serhanif59 approved these changes

2022-11-08 16:33 UTC, Benja-san requested changes

2022-11-08 16:33 UTC, Benja-san commented on public/assets/js/select-unicorn.js
> +const allena = document.getElementById('allena');
please use loop in order to avoid hardcode

2022-11-09 11:13 UTC, Benja-san approved these changes

2022-11-09 11:14 UTC, merged