responsive header
WildCodeSchool/yellowgreen pull request #5
Opened 2022-10-25 15:00 UTC by julie-jeancon-donon

2022-10-25 15:12 UTC, Benja-san requested changes

2022-10-25 15:12 UTC, Benja-san commented on public/assets/css/header.css
> +    font-family: 'Mali';
Please use global variables set by Mehdi on dev

2022-10-25 15:12 UTC, Benja-san commented on public/assets/css/header.css
> +    background-color: #facfcf;
Could you set a global variable since you're using this color for multiples items

2022-10-25 15:12 UTC, Benja-san commented on public/assets/css/header.css
> +    color: #f76c6c;
Use global variables set by Mehdi

2022-10-25 15:12 UTC, Benja-san commented on public/assets/css/header.css
> +    font-family:'roboto';
Use global fonts variables set by mehdi

2022-10-25 15:12 UTC, Benja-san commented on public/assets/css/header.css
> +header{
Use a classname or all the header tags of your website ill take this display

2022-10-25 15:12 UTC, Benja-san commented on public/assets/css/header.css
> +  aside{
Use a classname or all the aside tags of your website ill take this display

2022-10-25 15:12 UTC, Benja-san commented on public/assets/css/header.css
> +  header a img{
use header classname instead of tag name

2022-10-25 15:12 UTC, Benja-san commented on public/assets/css/header.css
> +    header{
use header classname as well

2022-10-25 15:12 UTC, Benja-san commented on src/View/layout.html.twig
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
See with Mehdi for font imports since he put the fonts inside css file as Import

2022-10-26 07:43 UTC, Benja-san requested changes

2022-10-26 07:43 UTC, Benja-san commented on public/assets/css/header.css
>    a{
If all the a tag have to take this behavior could you put it inside style.css which is the file for tags and class global behavior on all website

2022-10-26 08:10 UTC, Benja-san approved these changes

2022-10-26 08:16 UTC, marcosigis approved these changes
all good

2022-10-26 08:16 UTC, merged