Real fight2
WildCodeSchool/yellowgreen pull request #50
Opened 2022-11-09 18:12 UTC by serhanif59

2022-11-09 18:21 UTC, Benja-san requested changes

2022-11-09 18:21 UTC, Benja-san commented on src/View/Fight/select-unicorn.html.twig
> +					{{dump(unicorns)}}
no dump inside view file

2022-11-10 11:24 UTC, Benja-san approved these changes
Merge only if dump has been removed

2022-11-10 11:57 UTC, marcosigis approved these changes

2022-11-10 11:57 UTC, merged