first commit for us and footer
WildCodeSchool/yellowgreen pull request #6
Opened 2022-10-26 08:10 UTC by marcosigis

2022-10-26 15:05 UTC, julie-jeancon-donon requested changes
mettre les images random dans un dossier dans le gitignore

2022-10-26 15:08 UTC, julie-jeancon-donon approved these changes

2022-10-27 10:16 UTC, Benja-san requested changes
Use BEM for css files
What are all those pictures? needed for user avatar ? or useless pics ? 
Also I did not see where you remove the picture whene editing / deleting user

Most important thing :
This Branch is way too heavy!
Please next time use a branch for One US and split the work

2022-10-27 10:16 UTC, Benja-san commented on public/assets/css/footer.css
> +footer {
please use a className for the footer otherwise all the footer tags in all the pages will take this behavior

2022-10-27 10:16 UTC, Benja-san commented on public/assets/css/footer.css
> +footer a {
Use BEM with footer className

2022-10-27 10:16 UTC, Benja-san commented on public/assets/css/show.css
> +h1 {
If the H1 tag has a global behavior, please put it inside the global css file. Else it is fine

2022-10-27 10:16 UTC, Benja-san commented on public/assets/css/show.css
> +h1 a {
A cannot be a descendant of H1, it will be the opposite instead

2022-10-27 10:16 UTC, Benja-san commented on public/assets/css/show.css
> +    background-color: #f44336;
Use global variables (or set'em) available in global css files since you are using this color for multiples elements

2022-10-27 10:16 UTC, Benja-san commented on public/assets/css/show.css
> +    background-color: #474e5d;
same

2022-10-27 10:16 UTC, Benja-san commented on public/assets/css/show.css
> +    background-color: #fefefe;
same ?

2022-10-27 10:16 UTC, Benja-san commented on public/assets/js/confirmModale.js
> +    location.href = "delete?id={{ user.id }}";
Do you really need JS to do that ? You could just put an A tag with href ?

2022-10-27 10:16 UTC, Benja-san commented on src/Controller/HomeController.php
> +    public function add(): ?string
Since this method relates to User, please create a User/UserController class with index and add method
+ you have code duplication in your UserController (same add method)

2022-10-27 10:16 UTC, Benja-san commented on src/View/Home/index.html.twig
> +    {# <button style="button"> Je veux jouer ! </button> #}
dead code

2022-10-27 10:16 UTC, Benja-san commented on src/View/Home/index.html.twig
> -    <link rel="stylesheet" type="text/css" href="/assets/css/index.css"/>
use the twig parent functionality in order to keep the header / footer stlesheet inside the stylesheet content

2022-10-27 10:16 UTC, Benja-san commented on src/View/Home/index.html.twig
> +<script>
Please put this code inside  a js file.
Also, too much code repetition, prefer use some specific js files in order to import the functions where you need to.

2022-10-27 10:16 UTC, Benja-san commented on src/View/User/_addUserForm.html.twig
> +<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
Please Do Not Use JQuery for javascript interactions. Change this part of code from JQUERY to JS 
Please put this script into a JS file

2022-10-27 10:16 UTC, Benja-san commented on src/View/User/add.html.twig
> +    <h1>Add a new item</h1>
New User is not a new Item, change the Item folder by a User folder

2022-10-27 10:16 UTC, Benja-san commented on src/View/User/editUser.html.twig
> +{% extends 'layout.html.twig' %}
Remove all blank lines from this file

2022-10-27 10:16 UTC, Benja-san commented on src/View/User/show.html.twig
> +<div id="id01" class="modal">
change div tag by main tag

2022-10-27 10:16 UTC, Benja-san commented on src/View/User/show.html.twig
> +      <h3>Are you sure you want to delete your account {{user.nickName}}?</h3>
where are the h2 ?

2022-10-27 10:16 UTC, Benja-san commented on src/View/User/show.html.twig
> +  <h1>My Details <a href="/users/edit?id={{ user.id }}">✏️</a>  </h1>
Only one h1 by page

2022-10-27 10:16 UTC, Benja-san commented on src/View/User/show.html.twig
> +<script>
code repetition as well
Put the script into a file
optimize js

2022-10-27 14:17 UTC, Benja-san requested changes

2022-10-27 14:17 UTC, Benja-san commented on public/assets/css/footer.css
>  footer a {
use classname instead of footer tag

2022-10-27 14:17 UTC, Benja-san commented on public/assets/js/profilePic.js
> +$(document).ready(function () {
You will need to change it as soon as possible, ok just for client interview

2022-10-27 14:17 UTC, Benja-san commented on src/Controller/AbstractController.php
> +    public static function cleanParam(mixed $param): mixed
ali's work so ali's branch

2022-10-27 14:17 UTC, Benja-san commented on src/View/Fight/index.html.twig
> +{% extends 'layout.html.twig' %}
Remove it and let it for Ali's Branch

2022-10-27 14:17 UTC, Benja-san commented on src/View/User/_editUserForm.html.twig
> +{% block formsection %}
remove it and let it for Ali's Branch

2022-10-27 14:17 UTC, Benja-san commented on src/View/components/_header.html.twig
> +        <a href="/fights/" class="radiusButton">Combat</a>
You have to tell July to do taht on her branch

2022-10-27 14:52 UTC, julie-jeancon-donon approved these changes

2022-10-28 14:14 UTC, Benja-san requested changes

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/footer.css
> +    background-color: #FACFCF;
since u are using this color in multiple elements please put it as a global variable in global css file

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/show.css
> +     background: #FACFCF;
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/footer.css
> +    color: #DB6464;
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/footer.css
> +    background-color: #FACFCF;
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/show.css
> +     text-shadow: 0px 1px 0px #f54f4f;
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/show.css
> +     background: linear-gradient(to bottom, #bd5959 5%, #db6464 100%);
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/userForm.css
> +    background: #FACFCF;
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/userForm.css
> +    box-shadow: 0px 10px 14px -7px #db6464;
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/userForm.css
> +    text-shadow: 0px 1px 0px #f54f4f;
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/userForm.css
> +    background: linear-gradient(to bottom, #bd5959 5%, #db6464 100%);
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/userForm.css
> +    box-shadow: 0px 10px 14px -7px #494747;
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/userForm.css
> +    background-color: #db6464;
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/userForm.css
> +    background: linear-gradient(to bottom, #504d4d 5%, #6d6565 100%);
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/userForm.css
> +    text-shadow: 0px 1px 0px #1d1515;
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/userForm.css
> +    background: linear-gradient(to bottom, #2c2c2c 5%, #070505 100%);
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/userForm.css
> +    background-color: #1d1919;
global variable

2022-10-28 14:14 UTC, Benja-san commented on public/assets/css/userForm.css
> +}
Sounds like the user css files have buttons, modal and other behaviors in common, please refactor in order to have this code written only once (global css file)

2022-10-28 14:14 UTC, Benja-san commented on public/assets/js/profilePic.js
> +$(document).ready(function () {
this has to leave in profit of a vanilla js code

2022-10-28 14:14 UTC, Benja-san commented on src/Controller/UserController.php
>          if ($_SERVER['REQUEST_METHOD'] === 'POST') {
nothing to POST in index method since this method just displays the user

2022-10-28 14:14 UTC, Benja-san commented on src/View/Components/_footer.html.twig
> +{% block stylesheet %}
you don't need any stylesheet block inside footer view since you're importing it inside the layout

2022-10-28 14:14 UTC, Benja-san commented on src/View/Home/index.html.twig
> +  <link rel="stylesheet" type="text/css" href="/assets/css/footer.css"/>
this file has to be inside the layout stylesheet block and only there

2022-10-28 14:14 UTC, Benja-san commented on src/View/Home/index.html.twig
please add title block

2022-10-28 14:14 UTC, Benja-san commented on src/View/Home/index.html.twig
> +		    </div>
please indent properly

2022-10-28 14:14 UTC, Benja-san commented on src/View/User/_addUserForm.html.twig
> +{% block stylesheet %}
since this file is a component to include, please shift the stylesheet inside the page supposed to include this file

2022-10-28 14:14 UTC, Benja-san commented on src/View/User/_addUserForm.html.twig
> +{% block javascript %}
same as the stylesheet issue for components

2022-10-28 14:14 UTC, Benja-san commented on src/View/User/_editUserForm.html.twig
> +<link rel="stylesheet" href="/assets/css/userForm.css">
see comments about the _addUserForm component

2022-10-28 14:14 UTC, Benja-san commented on src/View/User/_editUserForm.html.twig
> +		<input type="hidden" value={{user.id}} name="id" id="id" placeholder="id" >
Optional : Since you're having the same form for add and edit, maybe you could create some macro to avoid code repetition

2022-10-28 14:14 UTC, Benja-san commented on src/View/User/add.html.twig
> +
please add title block

2022-10-28 14:14 UTC, Benja-san commented on src/View/User/addUser.html.twig
> +
please add title block

2022-10-28 14:14 UTC, Benja-san commented on src/View/User/add.html.twig
> +{% endblock %}
I'm pretty sure this file can be perfctly removed

2022-10-28 14:14 UTC, Benja-san commented on src/View/User/addUser.html.twig
> +{% extends 'layout.html.twig' %}
keep the simple method add and Add.html.twig

2022-10-28 14:14 UTC, Benja-san commented on src/View/User/editUser.html.twig
> +
add title block

2022-10-28 14:14 UTC, Benja-san commented on src/View/User/editUser.html.twig
> +{% extends 'layout.html.twig' %}
keep the simple method edit and edit.html.twig

2022-10-28 14:14 UTC, Benja-san commented on src/View/User/index.html.twig
> +
add title block

2022-10-28 14:14 UTC, Benja-san commented on src/View/User/show.html.twig
> +
please add title block

2022-10-28 14:14 UTC, Benja-san commented on src/View/User/show.html.twig
> +      <h1>Delete Account</h1>
only one h1 by page, and not really optimized to focus the main title of the page for a deletion title

2022-11-02 08:41 UTC, Benja-san requested changes
Only one change for global css in layout.html and It will be approved

2022-11-02 08:41 UTC, Benja-san commented on src/View/layout.html.twig
> +			<link rel="stylesheet" type="text/css" href="/assets/css/style.css">
This file must be outside the stylesheet block since it will be available on all the website

2022-11-02 09:36 UTC, Benja-san approved these changes

2022-11-02 09:38 UTC, merged