Rules page
WildCodeSchool/yellowgreen pull request #9
Opened 2022-10-26 14:39 UTC by thenriet

2022-10-26 15:12 UTC, julie-jeancon-donon approved these changes

2022-10-27 09:36 UTC, Benja-san requested changes
I assume you pulled the user US before to make your PR, it is fine for the first launch, next time only one US at a time should be PRed

2022-10-27 09:36 UTC, Benja-san commented on public/assets/css/rules.css
> +h1,
If h1 and h2 have this behavior in all website, please put it inside the global css file. Else it's fine

2022-10-27 09:36 UTC, Benja-san commented on public/assets/css/rules.css
> +h2 {
same

2022-10-27 09:36 UTC, Benja-san commented on public/assets/js/card-flip.js
> +console.log(textDivContent);
I assume console log is for debugging, you can remove'em before to push it on dev branch

2022-10-27 09:36 UTC, Benja-san commented on public/assets/js/card-flip.js
> +/*let result;
dead code

2022-10-27 09:36 UTC, Benja-san commented on public/assets/js/card-flip.js
> +    /*cardArray.forEach(element => {
dead code

2022-10-27 09:36 UTC, Benja-san commented on src/Controller/HomeController.php
> +    public function rules(): string
since rules is not part of the Home/index page, please create a Rules/RulesController class with an index method

2022-10-27 09:36 UTC, Benja-san commented on src/Controller/UserController.php
> +    public function index(): string
Optionnal : We saw in the yesterday workshop how to add a Global variable in twig and how to hydrate it on construct with the user (which u will need in all the methods / pages of the controller / views)

2022-10-27 09:36 UTC, Benja-san commented on src/Controller/UserController.php
> +        return $this->twig->render('user/index.html.twig', ['users' => $users]);
Please rename your user folder with capital U

2022-10-27 09:36 UTC, Benja-san commented on src/Controller/UserController.php
> +            $userManager->delete((int)$id);
if you typed your delete method with an INT you don't need to change $id type inside parameter

2022-10-27 09:36 UTC, Benja-san commented on src/View/Home/rules.html.twig
> +	<h1 class="rule-title">Bienvenue dans Happiness & Glitters</h1>
please wrap all your page content in a main tag

2022-10-27 09:36 UTC, Benja-san commented on src/View/Home/rules.html.twig
> +	<div class="rule">
since you have a list of rules, please wrap all your rules inside a ul tag and change the DIV tag in LI TAG for each Rule

2022-10-27 13:28 UTC, Benja-san requested changes

2022-10-27 13:28 UTC, Benja-san commented on public/assets/js/card-flip.js
> +console.log(blink.innerHTML);
debugging code has to be removed

2022-10-27 13:28 UTC, Benja-san commented on src/View/Rules/index.html.twig
> +	<link rel="stylesheet" href="/assets/css/rules.css">
you will need the parent function of twig in order to implement global header and footer css files as well

2022-10-27 13:28 UTC, Benja-san commented on src/View/Rules/index.html.twig
> +
please add the title block as well

2022-10-27 13:53 UTC, Benja-san approved these changes

2022-10-27 13:55 UTC, merged